apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::731141591000:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-37EE7B7XSRFM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters 
      rolearn: arn:aws:iam::731141591000:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-25T19:48:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1307"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fd8b710a-81a6-439f-9590-bea27d6d8b6d
